import CarSVG from '../assets/svg/cars.svg'
import TruckSVG from '../assets/svg/truck.svg'
import OtherCarSVG from '../assets/svg/other-car.svg'
import HatchbackCarSVG from '../assets/svg/hatchback.svg'
import CoupeCarSVG from '../assets/svg/coupe.svg'
import PickupCarSVG from '../assets/svg/pickup.svg'

export const years: any[] = []
for (let i = 2010; i <= 2021; i++) {
  years.push({ label: i, value: i })
}

export const transmissions: any[] = [
  { label: 'Все', value: '' },
  { label: 'Механічна', value: 'manual' },
  { label: 'Автоматична', value: 'automatic' },
]

export const driveLineTypes = [
  'Передній привід',
  'Задній привід',
  '4x4',
  'Повний привід',
]

export const gas: { label: string; value: string }[] = [
  { label: 'Все', value: '' },
  { label: 'Бензин', value: 'gas' },
  { label: 'Дизель', value: 'diesel' },
  { label: 'Гібрид', value: 'hybrid-engine' },
  { label: 'Електро', value: 'electric' },
  { label: 'Етанол 85', value: 'flexible-fuel' },
  { label: 'Газ', value: 'compressed-natural-gas' },
  { label: 'Конвертується на газ', value: 'convertible-to-gaseous-powered' },
  { label: 'Водень', value: 'hydrogen-fuel-cell' },
  { label: 'Зріджений газ', value: 'liquefied-petroleum-gas"' },
  { label: 'Інше', value: 'other' },
]

export const sort: { label: string; value: string }[] = [
  { label: 'Дата створення лота ↑', value: 'added-date--asc' },
  { label: 'Дата створення лота ↓', value: 'added-date--desc' },
  { label: 'Дата аукціона ↑', value: 'auction-date--asc' },
  { label: 'Дата аукціона ↓', value: 'auction-date--desc' },
  { label: 'Ставка ↑', value: 'current-bid--asc' },
  { label: 'Ставка ↓', value: 'current-bid--desc' },
  { label: 'Рік випуску ↑', value: 'year--asc' },
  { label: 'Рік випуску ↓', value: 'year--desc' },
  { label: 'Пробіг ↑', value: 'odometer--asc' },
  { label: 'Пробіг ↓', value: 'odometer--desc' },
]

export const vehicleTypes = [
  {
    title: 'Легкові',
    value: 'automobile',
    icon: CarSVG,
  },
  {
    title: 'Грузові',
    value: 'truck',
    icon: TruckSVG,
  },
  {
    title: 'Інші',
    value: 'other',
    icon: OtherCarSVG,
  },
]

export const bodyTypes = [
  { title: 'Седан', value: 'SEDAN', icon: CarSVG },
  { title: 'Хетчбек', value: 'HATCHBAC', icon: HatchbackCarSVG },
  { title: 'Купе', value: 'COUPE', icon: CoupeCarSVG },
  { title: 'Пікап', value: 'PICKUP', icon: PickupCarSVG },
  { title: 'Інші', value: 'OTHER', icon: CarSVG },
]

export const bodyTypeArray = [
  '(none)',
  '2 Door',
  '2dr Spor',
  '3 Door Extended Cab Pickup',
  '3dr Ext',
  '4 Door',
  '4 Door Extended Cab Chassis',
  '4 Door Extended Cab Pickup',
  '4dr Ext',
  '4dr Spor',
  'All Terr',
  'Bus',
  'Cab &amp; Chassis (luv)',
  'Cab Chassis 2 Door',
  'Cargo Va',
  'Cargo Van',
  'Chassis',
  'Club Cab',
  'Club Cab Pickup',
  'Club Cha',
  'Conventi',
  'Converti',
  'Convertible',
  'Convertible 2 Door',
  'Coupe',
  'Coupe 2 Door',
  'Coupe 3 Dr.',
  'Coupe 3d',
  'Coupe 4 Dr.',
  'Crew Cab Long Bed',
  'Crew Cha',
  'Crew Chassis',
  'Crew Pic',
  'Crew Pickup',
  'Crew Van/cargo Van',
  'Cutaway',
  'Enduro',
  'Extended',
  'Extended Cab Pickup',
  'Extended Cargo Van',
  'Extended Sport Van',
  'Extended Van',
  'Forward Control',
  'Hatchbac',
  'Hatchback 2 Door',
  'Hatchback 2 Dr.',
  'Hatchback 4 Door',
  'Hatchback 4 Dr.',
  'Hearse',
  'Incomp P',
  'Incomple',
  'Incomplete Chassis',
  'Incomplete Ext Van',
  'Liftback',
  'Liftback 3 Dr.',
  'Limousin',
  'Limousine',
  'Mega Pickup',
  'Motor Sc',
  'Motorize',
  'Multi-purpose',
  'Passenger Van',
  'Pickup',
  'Pickup 2 Door',
  'Pickup 4 Door',
  'Pickup Long Bed',
  'Pillard Hardtop 2 Dr.',
  'Pillard Hardtop 4 Dr.',
  'Quad Pickup',
  'Racer',
  'Road/str',
  'Roadster',
  'Sedan',
  'Sedan 2',
  'Sedan 2 Door',
  'Sedan 2 Dr.',
  'Sedan 4 Door',
  'Sedan 4 Dr.',
  'Sedan 4d',
  'Sedan 5 Dr.',
  'Sport Pi',
  'Sport Pickup',
  'Sport Utility',
  'Sports V',
  'Sports Van',
  'Station',
  'Station Wagon',
  'Step Van',
  'Super Cab Pickup',
  'Suv 2 Door',
  'Suv 4 Door',
  'Tilt Cab',
  'Tractor',
  'Utility',
  'Van',
  'Van Camp',
  'Van Cargo 3 Door',
  'Van Passenger',
  'Van Passenger 3 Door',
  'Van Passenger 4 Door',
  'Wagon',
  'Wagon 2 Dr.',
  'Wagon 4 Door',
  'Wagon 4 Dr.',
  'Wagon 4d',
  'Window Van',
]
